name: Sync K8s Rollout

on:
  workflow_dispatch:
    

jobs:
  k8s_apply:
    runs-on: ubuntu-latest
    env:
      DEPLOYMENT_NAME: ${{ secrets.DEPLOYMENT_NAME || 'content-engine' }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Kubectl
        uses: azure/setup-kubectl@v3
      - name: Configure Kubectl
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG }}" > ~/.kube/config
      - name: Setup K8s Secrets
        run: |
          export NEW_SECRET_VALUE=$(openssl rand -base64 32)
          cat <<EOF > k8s/1-secret.yaml
          apiVersion: v1
          kind: Secret
          metadata:
            name: content-engine-secret
          stringData:
            SECRET_KEY: $NEW_SECRET_VALUE
            DJANGO_DEBUG: "0"
          EOF
      - name: Apply K8s Manifests
        run: |
          kubectl apply -f k8s/
      - name: Trigger K8s Deployment Rollout
        run: |
          kubectl rollout restart deployments/${{ env.DEPLOYMENT_NAME }}
      - name: Verify K8s Deployment Rollout
        run: |
          kubectl rollout status deployments/${{ env.DEPLOYMENT_NAME }}